import { Dimensions } from "react-native";

export const SCREEN = {
  WIDTH: Dimensions.get("window").width,
  HEIGHT: Dimensions.get("window").height,
};

export const DECKS = {
  REQUEST_DECK_LIST: "REQUEST_DECK_LIST",
  REQUEST_DECK_LIST_SUCCESS: "REQUEST_DECK_LIST_SUCCESS",
  REQUEST_DECK_LIST_FAILURE: "REQUEST_DECK_LIST_FAILURE",
  REQUEST_DECK_LIST_RESET: "REQUEST_DECK_LIST_RESET",
};

export const CARDS = {
  REQUEST_ALL_CARDS: "REQUEST_ALL_CARDS",
  REQUEST_ALL_CARDS_SUCCESS: "REQUEST_ALL_CARDS_SUCCESS",
  REQUEST_ALL_CARDS_FAILURE: "REQUEST_ALL_CARDS_FAILURE",
  REQUEST_ALL_CARDS_RESET: "REQUEST_ALL_CARDS_RESET",
  FILTER_CARDS: "FILTER_CARDS",
};

export const PACKS = {
  REQUEST_ALL_PACKS: "REQUEST_ALL_PACKS",
  REQUEST_ALL_PACKS_SUCCESS: "REQUEST_ALL_PACKS_SUCCESS",
  REQUEST_ALL_PACKS_FAILURE: "REQUEST_ALL_PACKS_FAILURE",
  REQUEST_ALL_PACKS_RESET: "REQUEST_ALL_PACKS_RESET",
};
